from pathlib import Path


ROOT_PATH = Path(__file__).parent.parent
SETTINGS_PATH = ROOT_PATH / "settings.ini"
CLOSE_ICON_PATH = ROOT_PATH / "icons" / "close.svg"
SETTINGS_ICON_PATH = ROOT_PATH / "icons" / "settings.svg"


MUXERS = [('mp4', 'MP4 (MPEG-4 Part 14)'),
          ('mov', 'QuickTime / MOV'),
          ('mkv', 'Matroska'),
          ('avi', 'AVI (Audio Video Interleaved)'),
          ('webm', 'WebM'),
          ('mxf', 'MXF (Material eXchange Format)'),
          ('mpegts', 'MPEG-TS (MPEG-2 Transport Stream)'),
          ('ismv', 'ISMV/ISMA (Smooth Streaming)'),
          ('m4v', 'raw MPEG-4 video'),
          ('3gp', '3GP (3GPP file format)'),
          ('flv', 'FLV (Flash Video)'),
          ('f4v', 'F4V Adobe Flash Video'),
          ('mpeg', 'MPEG-1 Systems / MPEG program stream'),
          ('vob', 'MPEG-2 PS (VOB)'),
          ('ogv', 'Ogg Video'),
          ('ogg', 'Ogg'),
          ('hevc', 'raw HEVC video'),
          ('ivf', 'On2 IVF'),
          ('asf', 'ASF (Advanced / Active Streaming Format)'),
          ('rm', 'RealMedia')]


VIDEO_ENCODERS = [('libx264', 'libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10'),
                  ('libx264rgb', 'libx264 H.264 / AVC (RGB variant)'),
                  ('h264_nvenc', 'NVIDIA NVENC H.264 encoder'),
                  ('h264_amf', 'AMD AMF H.264 Encoder'),
                  ('h264_qsv', 'H.264 Intel Quick Sync Video'),
                  ('h264_mf', 'H.264 via MediaFoundation'),
                  ('libx265', 'libx265 H.265 / HEVC'),
                  ('hevc_nvenc', 'NVIDIA NVENC HEVC encoder'),
                  ('hevc_amf', 'AMD AMF HEVC encoder'),
                  ('hevc_qsv', 'HEVC Intel Quick Sync Video'),
                  ('hevc_mf', 'HEVC via MediaFoundation'),
                  ('libaom-av1', 'libaom AV1'),
                  ('libvpx-vp9', 'libvpx VP9'),
                  ('libvpx', 'libvpx VP8'),
                  ('vp9_qsv', 'VP9 Intel Quick Sync Video'),
                  ('prores_ks', 'Apple ProRes (iCodec Pro)'),
                  ('prores_aw', 'Apple ProRes (aw)'),
                  ('prores', 'Apple ProRes'),
                  ('dnxhd', 'VC3/DNxHD'),
                  ('mpeg4', 'MPEG-4 part 2'),
                  ('libxvid', 'libxvidcore MPEG-4 part 2'),
                  ('msmpeg4', 'MPEG-4 part 2 Microsoft variant v3'),
                  ('msmpeg4v2', 'MPEG-4 part 2 Microsoft variant v2'),
                  ('mpeg2video', 'MPEG-2 video'),
                  ('mpeg2_qsv', 'MPEG-2 video Intel Quick Sync Video'),
                  ('mpeg1video', 'MPEG-1 video'),
                  ('mjpeg', 'MJPEG (Motion JPEG)'),
                  ('mjpeg_qsv', 'MJPEG Intel Quick Sync Video'),
                  ('dvvideo', 'DV (Digital Video)'),
                  ('ffv1', 'FFmpeg video codec #1 (lossless)'),
                  ('huffyuv', 'Huffyuv / HuffYUV (lossless)'),
                  ('ffvhuff', 'Huffyuv FFmpeg variant (lossless)'),
                  ('utvideo', 'Ut Video (lossless)'),
                  ('magicyuv', 'MagicYUV video (lossless)'),
                  ('rawvideo', 'Raw video (uncompressed)'),
                  ('v210', 'Uncompressed 4:2:2 10-bit'),
                  ('r210', 'Uncompressed RGB 10-bit'),
                  ('r10k', 'AJA Kona 10-bit RGB Codec'),
                  ('avrp', 'Avid 1:1 10-bit RGB Packer'),
                  ('avui', 'Avid Meridien Uncompressed'),
                  ('ayuv', 'Uncompressed packed MS 4:4:4:4'),
                  ('v308', 'Uncompressed packed 4:4:4'),
                  ('v408', 'Uncompressed packed QT 4:4:4:4'),
                  ('v410', 'Uncompressed 4:4:4 10-bit'),
                  ('y41p', 'Uncompressed YUV 4:1:1 12-bit'),
                  ('yuv4', 'Uncompressed packed 4:2:0'),
                  ('bitpacked', 'Bitpacked'),
                  ('cfhd', 'GoPro CineForm HD'),
                  ('speedhq', 'NewTek SpeedHQ'),
                  ('vc2', 'SMPTE VC-2 / Dirac'),
                  ('libtheora', 'libtheora Theora'),
                  ('flv', 'FLV / Sorenson Spark / H.263 (Flash Video)'),
                  ('flashsv', 'Flash Screen Video'),
                  ('flashsv2', 'Flash Screen Video Version 2'),
                  ('h263p', 'H.263+ / H.263-1998'),
                  ('h263', 'H.263 / H.263-1996'),
                  ('h261', 'H.261'),
                  ('wmv2', 'Windows Media Video 8'),
                  ('wmv1', 'Windows Media Video 7'),
                  ('rv20', 'RealVideo 2.0'),
                  ('rv10', 'RealVideo 1.0'),
                  ('qtrle', 'QuickTime Animation (RLE)'),
                  ('rpza', 'QuickTime video (RPZA)'),
                  ('smc', 'QuickTime Graphics (SMC)'),
                  ('svq1', 'Sorenson Vector Quantizer 1 / SVQ1'),
                  ('cinepak', 'Cinepak'),
                  ('msvideo1', 'Microsoft Video-1'),
                  ('snow', 'Snow'),
                  ('zlib', 'LCL ZLIB (lossless)'),
                  ('zmbv', 'Zip Motion Blocks Video'),
                  ('roqvideo', 'id RoQ video'),
                  ('amv', 'AMV Video'),
                  ('cljr', 'Cirrus Logic AccuPak'),
                  ('asv2', 'ASUS V2'),
                  ('asv1', 'ASUS V1'),
                  ('wrapped_avframe', 'AVFrame to AVPacket passthrough'),
                  ('a64multi', 'Multicolor charset for Commodore 64'),
                  ('a64multi5', 'Multicolor charset for Commodore 64 (5th color)')]

IMAGE_ENCODERS = [('png', 'PNG (Portable Network Graphics)'),
                  ('gif', 'GIF (Graphics Interchange Format)'),
                  ('apng', 'APNG (Animated Portable Network Graphics)'),
                  ('bmp', 'BMP (Windows and OS/2 bitmap)'),
                  ('libwebp', 'libwebp WebP image'),
                  ('libwebp_anim', 'libwebp WebP image (animated)'),
                  ('exr', 'OpenEXR image'),
                  ('dpx', 'DPX (Digital Picture Exchange)'),
                  ('tiff', 'TIFF image'),
                  ('targa', 'Truevision Targa image'),
                  ('sgi', 'SGI image'),
                  ('jpeg2000', 'JPEG 2000'),
                  ('libopenjpeg', 'OpenJPEG JPEG 2000'),
                  ('jpegls', 'JPEG-LS'),
                  ('ljpeg', 'Lossless JPEG'),
                  ('ppm', 'PPM (Portable PixelMap)'),
                  ('pgm', 'PGM (Portable GrayMap)'),
                  ('pbm', 'PBM (Portable BitMap)'),
                  ('pam', 'PAM (Portable AnyMap)'),
                  ('pfm', 'PFM (Portable FloatMap)'),
                  ('pgmyuv', 'PGMYUV (Portable GrayMap YUV)'),
                  ('pcx', 'PC Paintbrush PCX image'),
                  ('alias_pix', 'Alias/Wavefront PIX image'),
                  ('fits', 'FITS (Flexible Image Transport System)'),
                  ('vbn', 'Vizrt Binary Image'),
                  ('sunrast', 'Sun Rasterfile image'),
                  ('xbm', 'XBM (X BitMap) image'),
                  ('xwd', 'XWD (X Window Dump) image'),
                  ('xface', 'X-face image')]
